services:
  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fullstackauthentication
    networks:
      - network
  backend:
    restart: on-failure
    build: ./backend
    networks:
      - network
  web:
    restart: on-failure
    build: 
      context: web
    networks:
      - network
  nginx:
    build: 
     context: nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    networks:
      - network
  # caddy:
  #   image: caddy:2.7.6-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "8081:80"
  #     #- "8081:443"
  #   volumes:
  #     - ./caddy:/etc/caddy
  #     #- ./site:/srv
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   networks:
  #     - network
volumes:
  caddy_data:
  caddy_config:
networks:
  network : 