services:
  db:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fullstackauthentication
    networks:
      - network
  backend:
    restart: on-failure
    build: ./backend
    networks:
      - network
  web:
    restart: on-failure
    build: 
      context: web
    networks:
      - network
  nginx:
    build: 
     context: nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    networks:
      - network
  
volumes:
  caddy_data:
  caddy_config:
networks:
  network : 