spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/fullstackauthentication
    username: root
    password:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  threads:
    virtual:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gitauk2@example.com
    password: hyjktlpjblpshsgz
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: 7000
#  address: 0.0.0.0  
  error:
    path: /user/error
    whitelabel:
      enabled: false

jwt:
  signing:
    key: KlqIoR9M1ssxtM0F1GeSOvZ6G3qS67CHHCSt6gzCeSM=


seed:
  data:
    path: src/main/resources/DatabaseSeed.json

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 30000
